### ISSUE TITLE
Add dev container for vstart

### ISSUE THREAD

**Issue by jlefevre** [uccross/skyhookdm-ceph-cls#51]
Add container for [vstart](https://docs.ceph.com/docs/master/dev/quick_guide/#developer-guide-quick) for interactive debugging and development.  Perhaps something like this, which requires Cmake "Debug" build instead of "Release" build.

```
- id: build-dev
  uses: docker://uccross/skyhookdm-builder:nautilus
  runs: [bash]
  env:
    CMAKE_FLAGS: "-DBOOST_J=4 -DCMAKE_BUILD_TYPE=Debug -DWITH_MANPAGE=OFF -DWITH_BABELTRACE=OFF -DWITH_MGR_DASHBOARD_FRONTEND=OFF"
    BUILD_THREADS: "4"
  args: [scripts/build.sh]
```

We should add another args script to build / run vstart.
